// js/rules/advantages.js
export const ADVANTAGES = [
  { name: 'Accurate Attack', category: 'Combat', desc: 'Trade off up to 5 points of effect rank for attack bonus.' },
  { name: 'Agile Feint', category: 'Skill', desc: 'Use Acrobatics or Agility to feint instead of Deception.' },
  { name: 'All-out Attack', category: 'Combat', desc: 'Trade off up to 5 points of active defense for attack bonus.' },
  { name: 'Assessment', category: 'Skill', desc: 'Use Insight to gauge an opponent\'s combat capabilities.' },
  { name: 'Benefit', category: 'General', desc: 'Social advantage, wealth, alternate identity, or official status.', ranked: true },
  { name: 'Chokehold', category: 'Combat', desc: 'Suffocate an opponent you have pinned or grabbed.' },
  { name: 'Close Attack', category: 'Combat', desc: '+1 bonus to all close attack checks per rank.', ranked: true },
  { name: 'Contacts', category: 'Skill', desc: 'Make an Investigation check in one minute using an established network.' },
  { name: 'Daze', category: 'Skill', desc: 'Use Deception or Intimidation to daze an opponent.' },
  { name: 'Defensive Attack', category: 'Combat', desc: 'Trade off up to 5 points of attack bonus for active defense.' },
  { name: 'Defensive Roll', category: 'Combat', desc: '+1 active bonus to Toughness per rank while not defenseless.', ranked: true },
  { name: 'Diehard', category: 'General', desc: 'Automatically stabilize when dying.' },
  { name: 'Eidetic Memory', category: 'General', desc: '+5 to remember things seen or heard; visual and audio recall.' },
  { name: 'Equipment', category: 'General', desc: '5 Equipment Points (EP) per rank for gear and weapons.', ranked: true },
  { name: 'Evasion', category: 'Combat', desc: '+2 circumstance bonus to active defense vs. area effects per rank (max 2).', ranked: true, maxRanks: 2 },
  { name: 'Extraordinary Effort', category: 'Fortune', desc: 'Gain two benefits when spending a hero point for extra effort.' },
  { name: 'Fascinate', category: 'Skill', desc: 'Entrall an audience using a chosen interaction skill or performance.' },
  { name: 'Fast Feint', category: 'Combat', desc: 'Feint as a move action with no penalty.' },
  { name: 'Favored Environment', category: 'Combat', desc: '+2 bonus to attack checks or active defense in chosen environment.' },
  { name: 'Favored Foe', category: 'Skill', desc: '+2 circumstance bonus to checks involving chosen creature type or organization.', ranked: true },
  { name: 'Fearless', category: 'General', desc: 'Immune to all fear effects.' },
  { name: 'Grab Fighting', category: 'Combat', desc: 'Maintain a grab with one arm and retain full defense.' },
  { name: 'Great Endurance', category: 'General', desc: '+5 bonus on checks against environmental hazards, starvation, or fatigue.' },
  { name: 'Hide in Plain Sight', category: 'Skill', desc: 'Hide while being observed without needing distraction.' },
  { name: 'Improved Aim', category: 'Combat', desc: 'Double circumstance bonuses gained from aiming.' },
  { name: 'Improved Critical', category: 'Combat', desc: 'Expand critical hit range by 1 per rank (e.g., 19-20).', ranked: true },
  { name: 'Improved Defense', category: 'Combat', desc: '+2 bonus to active defenses when using the Defend action.' },
  { name: 'Improved Disarm', category: 'Combat', desc: 'No penalty on attack check to disarm; target cannot disarm you in return.' },
  { name: 'Improved Grab', category: 'Combat', desc: 'Make a grab check as a free action following a successful unarmed attack.' },
  { name: 'Improved Hold', category: 'Combat', desc: 'Opponents suffer a -5 penalty on checks to escape your grab.' },
  { name: 'Improved Initiative', category: 'Combat', desc: '+4 bonus to Initiative checks per rank.', ranked: true },
  { name: 'Improved Smash', category: 'Combat', desc: 'No penalty on attack checks targeting objects; damage objects freely.' },
  { name: 'Improved Trip', category: 'Combat', desc: 'No penalty on trip check; target cannot trip you in return.' },
  { name: 'Inspire', category: 'Fortune', desc: '+1 circumstance bonus to allies per rank (max 5) for one round.', ranked: true, maxRanks: 5 },
  { name: 'Instant Up', category: 'Combat', desc: 'Stand up from prone as a free action without an Acrobatics check.' },
  { name: 'Interpose', category: 'Combat', desc: 'Move between an ally and an attack to take the hit for them.' },
  { name: 'Jack-of-all-trades', category: 'Skill', desc: 'Use any skill untrained without penalty.' },
  { name: 'Leadership', category: 'Fortune', desc: 'Spend a hero point to remove a condition or fatigue from an ally.' },
  { name: 'Luck', category: 'Fortune', desc: 'Reroll one check per rank per session (max ranks = 1/2 PL).', ranked: true },
  { name: 'Move-by Action', category: 'Combat', desc: 'Move before and after a standard action during your turn.' },
  { name: 'Power Attack', category: 'Combat', desc: 'Trade off up to 5 points of attack bonus for effect rank.' },
  { name: 'Precise Attack', category: 'Combat', desc: 'Ignore cover or concealment penalties for close or ranged attacks.', ranked: true },
  { name: 'Prone Fighting', category: 'Combat', desc: 'No penalty on attack checks or defense while prone.' },
  { name: 'Quick Draw', category: 'Combat', desc: 'Draw a weapon as a free action.' },
  { name: 'Ranged Attack', category: 'Combat', desc: '+1 bonus to all ranged attack checks per rank.', ranked: true },
  { name: 'Redirect', category: 'Combat', desc: 'Trick an opponent into striking another target on a failed attack.' },
  { name: 'Seize Initiative', category: 'Fortune', desc: 'Spend a hero point to automatically act first in initiative.' },
  { name: 'Set-up', category: 'Combat', desc: 'Transfer bonus from feint or demoralize to an ally.', ranked: true },
  { name: 'Skill Mastery', category: 'Skill', desc: 'Make routine checks with chosen skills even under pressure.' },
  { name: 'Startle', category: 'Combat', desc: 'Use Intimidation to feint in combat as a standard action.' },
  { name: 'Takedown', category: 'Combat', desc: 'Gain an immediate free attack against another minion after defeating one.', ranked: true },
  { name: 'Taunt', category: 'Combat', desc: 'Use Deception to demoralize an opponent in combat.' },
  { name: 'Teamwork', category: 'General', desc: '+5 circumstance bonus to team checks instead of the normal +2.' },
  { name: 'Throwing Mastery', category: 'Combat', desc: '+1 damage rank to thrown weapons per rank.', ranked: true },
  { name: 'Tracking', category: 'Skill', desc: 'Use Perception to follow visual and non-visual tracks.' },
  { name: 'Trance', category: 'General', desc: 'Enter a meditative state that lowers metabolism and vital signs.' },
  { name: 'Ultimate Effort', category: 'Fortune', desc: 'Spend a hero point to automatically treat check result as 20 on chosen roll.' },
  { name: 'Uncanny Dodge', category: 'Combat', desc: 'Retain active defense even while surprised or vulnerable.' },
  { name: 'Well-informed', category: 'Skill', desc: 'Make immediate Investigation check to know details about a person/place.' }
];

export const ADVANTAGE_CATEGORIES = ['All', 'Combat', 'Fortune', 'General', 'Skill', 'Ranked'];

export const ADVANTAGE_COST_PER_RANK = 1;

